#!/usr/bin/env python

import fileinput
import os
import re
import sys

tag = "LICENSE"

existing_block_re = re.compile("^\s*#* <LICENSE>.*</LICENSE>\n", flags=re.MULTILINE | re.DOTALL)

license = """\


# <LICENSE>
# Copyright 2018 HGVS Contributors (https://github.com/biocommons/hgvs)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# </LICENSE>
"""


if __name__ == "__main__":
    for fn in sys.argv[1:]:
        c = open(fn).read()
        c = existing_block_re.sub(license, c)
        open(fn, "w").write(c)
        
