- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "keep alive"
  color: "666666"
  description: "exempt issue from staleness checks"
  from_name: "keep alive"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "rfc"
  color: "d876e3"
  description: "Request for comments"

- name: "stale"
  color: "777777"
  description: "Issue is stale and subject to automatic closing"
  from_name: "Stale"

- name: "stale closed"
  color: "444444"
  description: "Issue was closed automatically due to inactivity"
  from_name: "stale-closed"

- name: "won't fix"
  color: "ffffff"
  description: "This will not be worked on"
  from_name: wontfix