repos:
# disabled for now due to excessive errors reported with new version
# - repo: local
#   hooks:
#     -  id: pyright
#        name: pyright
#        entry: pyright
#        language: system
#        types: [python]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
