[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 70.1", "setuptools_scm[toml] ~= 8.1"]

[dependency-groups]
dev = [
  "deptry>=0.23",
  "ipython",
  "jupyter",
  "mkdocs-awesome-nav>=3.1.2",
  "mkdocs-material>=9.6",
  "mkdocs>=1.6",
  "mkdocstrings[python]>=0.30",
  "mypy>=1.17",
  "pre-commit>=3.8",
  "pytest-cov>=4.1",
  "pytest-recording",
  "pytest>=7.4,<10.0",
  "ruff>=0.12",
  "sphinx",
  "sphinx_rtd_theme",
  "sphinxcontrib-fulltoc >= 1.1",
  "toml-sort",
  "tox-uv>=1.28",
  "vcrpy",
]

[project]
authors = [
  {email = "biocommons-dev@googlegroups.com", name = "biocommons contributors"}
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "Topic :: Scientific/Engineering :: Medical Science Apps.",
  "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = [
  "attrs >= 17.4.0", # https://github.com/biocommons/hgvs/issues/473
  "biocommons.seqrepo >= 0.6.10",
  "bioutils >= 0.4.0,<1.0",
  "importlib_resources",
  "ipython",
  "parsley",
  "psycopg[binary]",
  "psycopg-pool",
  "pyparsing >= 3.1",
]
description = "HGVS Parser, Formatter, Mapper, Validator"
dynamic = ["version"]
keywords = [
  "biocommons",
  "bioinformatics",
  "computational biology",
  "genome variation",
  "genomics",
  "hgvs",
  "variation"
]
license = "Apache-2.0"
name = "hgvs"
readme = "README.md"
requires-python = ">=3.11, <3.14"  # as-of 2025-11-02, PyO3 fails to build pydantic on 3.14

[project.optional-dependencies]
align = ["uta-align~=0.3"]

[project.scripts]
"hgvs-shell" = "hgvs.shell:shell"

[project.urls]
Documentation = "https://hgvs.readthedocs.io/"
Homepage = "https://github.com/biocommons/hgvs/"
Issues = "https://github.com/biocommons/hgvs/issues/"
Repository = "https://github.com/biocommons/hgvs/"

[tool.coverage]

[tool.coverage.report]
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",

    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if __name__ == .__main__.:",
]
show_missing = true
skip_empty = true

[tool.coverage.run]
branch = true
omit = [
  "*_test.py",
  "*/test/*",
  "*/tests/*",

  "hgvs/__init__.py",
  "hgvs/dataproviders/interface.py",
  "hgvs/dataproviders/ncbi.py",
  "hgvs/dataproviders/uta.py",
  "hgvs/decorators/*",
  "hgvs/intervalmapper.py",
  "hgvs/shell.py",
  "hgvs/transcriptmapper.py",
  "hgvs/utils/PersistentDict.py",
  "hgvs/utils/context.py",
  "hgvs/utils/orderedenum.py"
]
source = ["src"]

[tool.deptry]

[tool.deptry.package_module_name_map]
# map package name to import name
# Making this explicit suppresses deptry notices
coloredlogs = "coloredlogs"
mkdocs = "mkdocs"
mkdocs-material = "mkdocs_material"
mkdocstrings = "mkdocstrings"
mypy = "mypy"
pre-commit = "pre_commit"
pytest = "pytest"
pytest-cov = "pytest_cov"
pyyaml = "yaml"
ruff = "ruff"
tox-uv = "tox_uv"
ty = "ty"

[tool.pytest.ini_options]
addopts = "-s -v -x --strict-markers -m 'not extra' --doctest-modules --cov=src"
doctest_optionflags = [
  "ALLOW_BYTES",
  "ALLOW_UNICODE",
  "ELLIPSIS",
  "IGNORE_EXCEPTION_DETAIL",
  "NORMALIZE_WHITESPACE"
]
markers = [
  "network: tests that require network connectivity",
  "slow: slow tests that should be run infrequently",

  "extra",
  "issues",
  "mapping",
  "models",
  "normalization",
  "quick",
  "regression",
  "validation",
]
testpaths = ["tests"]

[tool.ruff]
extend-exclude = ["src/hgvs/parsers/generated"]
fix = true
line-length = 100
src = ["src", "tests"]
target-version = "py313"

[tool.ruff.format]
docstring-code-format = true
preview = true
quote-style = "double"

[tool.ruff.lint]
fixable = [
  "B",
  "C4",
  "D",
  "EM",
  "F401",
  "F541",
  "I",
  "PERF",
  "PIE",
  "PT",
  "RET",
  "RSE",
  "RUF",
  "SIM",
  "UP"
]
ignore = [
  "E111",
  "E114",
  "E117",
  "E501",
  "E731",
  "N801",
  "N802",
  "PLR0913",
  "RET504",
  "S321",
  "W191",
]
select = [
  "A", # https://docs.astral.sh/ruff/rules/#flake8-builtins-a
  "ARG", # https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg
  "B", # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
  "C4", # https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
  "DTZ", # https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz
  "E",
  "EM", # https://docs.astral.sh/ruff/rules/#flake8-errmsg-em
  "F", # https://docs.astral.sh/ruff/rules/#pyflakes-f
  "G", # https://docs.astral.sh/ruff/rules/#flake8-logging-format-g
  "I", # https://docs.astral.sh/ruff/rules/#isort-i
  "LOG", # https://docs.astral.sh/ruff/rules/#flake8-logging-log
  "N", # https://docs.astral.sh/ruff/rules/#pep8-naming-n
  "PERF", # https://docs.astral.sh/ruff/rules/#perflint-perf
  "PIE", # https://docs.astral.sh/ruff/rules/#flake8-pie-pie
  "PL", # https://docs.astral.sh/ruff/rules/#pylint-pl
  "PT", # https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
  "PTH", # https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
  "RET", # https://docs.astral.sh/ruff/rules/#flake8-return-ret
  "RSE", # https://docs.astral.sh/ruff/rules/#flake8-raise-rse
  "RUF", # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
  "S", # https://docs.astral.sh/ruff/rules/#flake8-bandit-s
  "SIM", # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
  "TRY", # https://docs.astral.sh/ruff/rules/#tryceratops-try
  "UP", # https://docs.astral.sh/ruff/rules/#pyupgrade-up
  "W", # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
  "YTT" # https://docs.astral.sh/ruff/rules/#flake8-2020-ytt
]

[tool.ruff.lint.per-file-ignores]
# https://github.com/biocommons/hgvs/issues/838
"tests/*" = ["PLR2004", "S101"]
"src/hgvs/__init__.py" = ["B028", "G003", "UP031", "UP036"]
"src/hgvs/alignmentmapper.py" = ["EM101", "EM102", "PLC0415", "PLR0911", "PLR0912", "PLR0915", "S101", "SIM102", "SIM108", "TRY003"]
"src/hgvs/assemblymapper.py" = ["B026", "C401", "EM102", "G003", "S101", "TRY003", "UP008"]
"src/hgvs/config.py" = ["B904", "G003"]
"src/hgvs/dataproviders/interface.py" = ["EM102", "G004", "PLR2004", "S101", "TRY003"]
"src/hgvs/dataproviders/ncbi.py" = ["ARG002", "C408", "EM102", "G003", "G004", "PLR2004", "PTH119", "RUF012", "TRY002", "TRY003", "UP008"]
"src/hgvs/dataproviders/seqfetcher.py" = ["B904", "EM102", "G003", "PLC0415", "TRY003"]
"src/hgvs/dataproviders/uta.py" = ["C408", "EM102", "G003", "G004", "PLR2004", "PLR5501", "PTH119", "RUF012", "SIM102", "TRY002", "TRY003", "UP008"]
"src/hgvs/decorators/lru_cache.py" = ["A002", "B006", "B008", "C408", "N806", "PLR0915"]
"src/hgvs/edit.py" = ["ARG002", "EM101", "PLR0912", "PLR5501", "S101", "TRY003"]
"src/hgvs/extras/babelfish.py" = ["EM102", "TRY003"]
"src/hgvs/hgvsposition.py" = ["UP030"]
"src/hgvs/location.py" = ["ARG002", "EM101", "N805", "PLR0911", "PLR0912", "PLR1714", "PLW1641", "S101", "SIM102", "SIM108", "TRY003", "TRY300", "UP030", "UP031"]
"src/hgvs/normalizer.py" = ["A001", "EM101", "EM102", "G004", "PLR0912", "PLR0915", "PLR1714", "PLR2004", "PLR5501", "S101", "SIM102", "TRY003", "TRY300"]
"src/hgvs/parser.py" = ["B904", "EM102", "G001", "PTH123", "TRY003", "UP031"]
"src/hgvs/parsers/base.py" = ["ARG004", "G001", "PLC0415", "UP031"]
"src/hgvs/parsers/generated/hgvs_grammar.py" = ["N803", "N806", "PLR0915", "S307"]
"src/hgvs/parsers/parsley_parser.py" = ["PLC0415", "PTH123"]
"src/hgvs/parsers/pyparsing_parser.py" = ["ARG002"]
"src/hgvs/posedit.py" = ["SIM108", "UP030"]
"src/hgvs/pretty/console/chromseqrenderer.py" = ["PLC0415", "SIM108"]
"src/hgvs/pretty/console/chromseqreverserenderer.py" = ["PLC0415", "SIM108"]
"src/hgvs/pretty/console/protseqrenderer.py" = ["PLC0415", "PLR0912", "PLR0915"]
"src/hgvs/pretty/console/shuffledvariant.py" = ["PLC0415", "PLR0912", "PLR0915"]
"src/hgvs/pretty/console/txaligrenderer.py" = ["PLC0415", "PLR0912", "PLR0915", "PLR1714", "PLR5501"]
"src/hgvs/pretty/console/txrefdisagreerenderer.py" = ["PLC0415", "PLR5501"]
"src/hgvs/pretty/datacompiler.py" = ["ARG002", "EM102", "PLR0402", "PLR0912", "PLR0915", "PLR1730", "PLR2004", "PLR5501", "RUF013", "SIM108", "TRY003"]
"src/hgvs/pretty/prettyprint.py" = ["A002", "PLR0912", "PLR0915", "PLR1704", "PLR1714", "RET503", "RUF013", "SIM102", "SIM108"]
"src/hgvs/repeats.py" = ["PLR0912", "PLR0915"]
"src/hgvs/sequencevariant.py" = ["A001", "SIM108", "UP030"]
"src/hgvs/shell.py" = ["PLC0415"]
"src/hgvs/utils/PersistentDict.py" = ["B904", "N999", "PTH123", "S301"]
"src/hgvs/utils/altseq_to_hgvsp.py" = ["EM101", "EM102", "PLR0912", "PLR0915", "PLR5501", "SIM108", "TRY003"]
"src/hgvs/utils/altseqbuilder.py" = ["B904", "EM101", "EM102", "N806", "PLR1714", "PLR5501", "RUF046", "TRY003"]
"src/hgvs/utils/cigarmapper.py" = ["EM101", "TRY003"]
"src/hgvs/utils/context.py" = ["A002", "EM102", "PLC0415", "PLR2004", "PT018", "S101", "SIM108", "TRY003"]
"src/hgvs/utils/norm.py" = ["PLR2004"]
"src/hgvs/utils/orderedenum.py" = ["S101"]
"src/hgvs/utils/position.py" = ["PLR0911", "PLR0912", "PLR5501", "SIM108", "UP038"]
"src/hgvs/utils/validation.py" = ["A002", "S101"]
"src/hgvs/validator.py" = ["G004", "S101"]
"src/hgvs/variantmapper.py" = ["PLR0912", "PLR0915"]

[tool.setuptools]
include-package-data = true
package-dir = {"" = "src"}
zip-safe = true

[tool.setuptools.package-data]
# "*" = ["_data/*/*.json.gz"]
# "*" = ["*.gz", "*.json", "*.yaml"]
"*" = ["_data/*"]

[tool.setuptools.packages.find]
exclude = ["*.pyc", "__pycache__"]
where = ["src"]

[tool.setuptools_scm]

[tool.sphinx-build]
all-files = true

[tool.wheel]
universal = 1
