#!/usr/bin/env python

import hgvs
import hgvs.dataproviders.uta
import hgvs.parser
import hgvs.transcriptmapper
import hgvs.sequencevariant
import hgvs.variantmapper

hdp = hgvs.dataproviders.uta.connect()
hp = hgvs.parser.Parser()
evm = hgvs.variantmapper.AssemblyMapper(hdp,
                                           replace_reference=True, assembly_name='GRCh37',
                                           alt_aln_method='splign')

v = hp.parse_hgvs_variant("NM_000302.3:c.1594_1596del")
evm.c_to_p(v)
