#!/usr/bin/env python
# generate json mapping of seguid => [protein accessions]

import collections
import hashlib
import json
import re
import sys

from Bio import SeqIO
from Bio.SeqUtils.CheckSum import seguid

ref_re = re.compile(r'ref\|([^|]+)')

seguid_acs = collections.defaultdict(lambda: set())

for record in SeqIO.parse(sys.stdin, "fasta") :
    hash = seguid(record.seq.tostring())
    ref_ac = ref_re.search(record.id).group(1)
    seguid_acs[hash].add(ref_ac)

seguid_acs = dict( (k,list(v)) for k,v in seguid_acs.iteritems() )

print( json.dumps(seguid_acs, indent=2, sort_keys=True) )
