#!/usr/bin/env python
# This generates the hgvs.parsers.Parser Python code from the OMeta grammar file
# We generate it offline then keep the statically generated file to reduce startup time
# @see https://github.com/biocommons/hgvs/issues/661

import hashlib
import sys
from pathlib import Path

import parsley
from ometa.builder import writePython
from ometa.grammar import OMeta

if __name__ == "__main__":
    script_path = Path(__file__).resolve()
    hgvs_base_dir = script_path.parent.parent
    grammar_file = hgvs_base_dir / "src/hgvs/parsers/_data/hgvs.pymeta"
    generated_code_dir = hgvs_base_dir / "src/hgvs/parsers/generated"

    grammar_hash = hashlib.md5(grammar_file.read_bytes(), usedforsecurity=False).hexdigest()
    prefix_length = len(str(hgvs_base_dir)) + 1  # extra to also remove slash

    header_template = """# --------------------------------------------------
# THIS IS A GENERATED FILE. DO NOT MODIFY.
# Changes will be overwritten by the generation script.
#    Generated by: {generate_script}
#    Grammar file: {grammar_file}
#    Grammar hash: {grammar_hash}
# Parsley version: {parsley_version}
#  Python version: {python_version}
# --------------------------------------------------
"""
    header = header_template.format(
        generate_script=str(script_path)[prefix_length:],
        grammar_file=str(grammar_file)[prefix_length:],
        grammar_hash=grammar_hash,
        parsley_version=parsley.__version__,
        python_version=sys.version,
    )

    g = OMeta(grammar_file.read_text(), name="Grammar")
    tree = g.parseGrammar("Grammar")
    source = writePython(tree, "Grammar")

    # Create a package for the new file for Python2 compatability
    if not generated_code_dir.exists():
        generated_code_dir.mkdir()
        package_filename = generated_code_dir / "__init__.py"
        package_filename.touch()

    source_filename = generated_code_dir / "hgvs_grammar.py"
    with source_filename.open("w") as source_file:
        source_file.write(header + "\n")
        source_file.write(source)
