#!/usr/bin/env perl
# extract-makefile-documentation -- extract doc from a makefile
# This script prints the header, up to the first empty line AND prints
# line starting with #=, and indented by an optional number of >.

my $print = 1;
while (<>) {
  next if ($. == 1 and m/^\#!/);
  print if ($print or s/^\#=([>]*)\s+/'  ' x length($1)/e);
  $print = 0 if m/^$/;
}


# <LICENSE>
# Copyright 2014 Contributors
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# </LICENSE>
